services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7712104265:AAF2999juz76IU9MloLpgsBQWgMJklI5XeM
      - key: SHEET_ID
        value: 1n89yGxSXW1uBFmGBWuheXNmi4oPuhXqwnJQB3t7VQeo
      - key: WEBHOOK_URL
        value: https://telegram-finance-bot-0ify.onrender.com
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json
    plan: free
    secretFiles:
      - name: gspread_key.json
        mountPath: /etc/secrets/gspread_key.json
