services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WEBHOOK_URL
        value: https://telegram-finance-bot-0ify.onrender.com
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json
      - key: SHEET_ID
        value: your_google_sheet_id_here  # Замените на реальный ID таблицы
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here  # Замените на реальный токен бота
    secretFiles:
      - name: gspread_key.json
        mountPath: /etc/secrets
    plan: free
