services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SHEET_NAME
        sync: false
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json
    secretFiles:
      - name: gspread_key.json
        mountPath: /etc/secrets/gspread_key.json
