services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WEBHOOK_URL
        value: https://telegram-finance-bot-0ify.onrender.com
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json
    secrets:
      - name: telegram-bot-secret
        envVar: BOT_TOKEN
      - name: google-sheet-secret
        envVar: SHEET_ID
    plan: free
    secretFiles:
      - name: gspread_key.json
        mountPath: /etc/secrets
