services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        valueFrom: 7712104265:AAF2999juz76IU9MloLpgsBQWgMJklI5XeM
          secretKeyRef:
            name: telegram-bot-token
            key: BOT_TOKEN
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json
      - key: SHEET_NAME
        value: hesabla
      - key: WEBHOOK_URL
        value: https://telegram-finance-bot-0ify.onrender.com
    plan: free
    secrets:
      - name: gspread-service-account
        fileName: gspread_key.json
        mountPath: /etc/secrets
