services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free

    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegram-secrets
            key: BOT_TOKEN
      - key: SHEET_ID
        valueFrom:
          secretKeyRef:
            name: telegram-secrets
            key: SHEET_ID
      - key: WEBHOOK_URL
        valueFrom:
          secretKeyRef:
            name: telegram-secrets
            key: WEBHOOK_URL
      - key: CREDS_FILE
        value: /etc/secrets/gspread_key.json

    secretFiles:
      - name: telegram-secrets
        mountPath: /etc/secrets
        files:
          - name: gspread_key.json
            path: gspread_key.json
